FROM node:19.1.0-slim

ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

ARG NEXT_AUTH_SECRET
ENV NEXT_AUTH_SECRET=$NEXT_AUTH_SECRET

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL

ARG SPOTIFY_ID
ENV SPOTIFY_ID=$SPOTIFY_ID

ARG SPOTIFY_SECRET
ENV SPOTIFY_SECRET=$SPOTIFY_SECRET

ARG SPOTIFY_OAUTH_CALL_BACK_URL
ENV SPOTIFY_OAUTH_CALL_BACK_URL=$SPOTIFY_OAUTH_CALL_BACK_URL

ARG SPOTIFY_API_URL
ENV SPOTIFY_API_URL=$SPOTIFY_API_URL

WORKDIR /app

COPY yarn.lock yarn.lock
COPY package.json package.json

RUN yarn

COPY tsconfig.json tsconfig.json
COPY next.config.js next.config.js
COPY .eslintrc.json .eslintrc.json
COPY src src
COPY public public

RUN yarn build

CMD ["yarn" "start"]