export const MUSIC_GENRES = {
    'blues': [
        'blues rock',
        'chicago blues',
        'country blues',
        'delta blues',
        'gospel blues',
        'japanese blues',
        'memphis blues',
        'modern blues',
        'texas blues',
        'traditional blues'
    ],
    'classical': [
        'baroque',
        'chamber orchestra',
        'early modern classical',
        'early romantic era',
        'late romantic era',
        'medieval',
        'neoclassicism',
        'opera',
        'renaissance'
    ],
    'country': [
        'alternative country',
        'country blues',
        'country rap',
        'honky tonk',
        'outlaw country',
        'truck-driving country',
        'western swing'
    ],
    'disco': [
        'boogie',
        'disco house',
        'disco polo',
        'future funk',
        'new italo disco',
        'nu disco',
        'post-disco'
    ],
    'edm': [
        'chiptune',
        'drum and bass',
        'dubstep',
        'electro',
        'hardstyle',
        'synthwave',
        'vaporwave'
    ],
    'house': [
        'acid house',
        'ambient house',
        'deep house',
        'electro house',
        'future house',
        'microhouse',
        'progressive house'
    ],
    'jazz': [
        'acid jazz',
        'afrobeat',
        'avant-garde jazz',
        'bepop',
        'cool jazz',
        'dixieland',
        'free jazz',
        'hard bop',
        'jazz funk',
        'jazz fusion',
        'jazz rap',
        'ska jazz',
        'soul jazz',
        'stride',
        'swing'
    ],
    'metal': [
        'avant-garde metal',
        'black metal',
        'christian metal',
        'crust punk',
        'death metal',
        'deathcore',
        'djent',
        'doom metal',
        'electronicore',
        'folk metal',
        'funk metal',
        'glam metal',
        'gothic metal',
        'grindcore',
        'groove metal',
        'heavy metal',
        'industrial metal',
        'mathcore',
        'melodic metalcore',
        'nu metal',
        'nu-metalcore',
        'post-metal',
        'power metal',
        'progressive metal',
        'progressive metalcore',
        'rap metal',
        'thrash metal'
    ],
    'pop': [
        'art pop',
        'bubblegum pop',
        'dance pop',
        'electropop',
        'indie pop',
        'jazz pop',
        'operatic pop',
        'pop house',
        'pop rock',
        'pop soul',
        'schlager',
        'sunshine pop',
        'synthpop',
        'teen pop',
        'variete francaise',
        'wonky'
    ],
    'rap': [
        'alternative hip hop',
        'bounce',
        'chopped and screwed',
        'christian hip hop',
        'dirty south rap',
        'drill',
        'experimental hip hop',
        'gangster rap',
        'harcore hip hop',
        'horrorcore',
        'industrial hip hop',
        'nerdcore',
        'political hip hop',
        'rap conscient',
        'trap',
        'underground rap'
    ],
    'reggae': [
        'dub',
        'early reggae',
        'lovers rock',
        'reggae fusion',
        'reggaeton',
        'rocksteady',
        'roots reggae',
        'ska'
    ],
    'rock': [
        'alternative rock',
        'christian rock',
        'classic rock',
        'experimental rock',
        'garage rock',
        'glam rock',
        'grunge',
        'hard rock',
        'new wave',
        'progressive rock',
        'psychedelic rock',
        'punk rock',
        'rockabilly',
        'soft rock',
        'southern rock',
        'space rock',
        'stoner rock',
        'surf music'
    ],
    'soul': [
        'motown',
        'neo soul',
        'nu jazz',
        'psychedelic soul',
        'quiet storm',
        'retro soul',
        'swamp rock'
    ],
    'techno': [
        'acid techno',
        'ambient techno',
        'detroit techno',
        'hardcore techno',
        'industrial techno',
        'minimal techno',
        'tech house'
    ],
    'trance': [
        'dark psytrance',
        'forest psy',
        'full on',
        'goa trance',
        'hard trance',
        'progressive trance',
        'psydub',
        'psytrance',
        'tech trance',
        'zenonesque'
    ]
};

export const MAIN_MUSIC_GENRES = Object.keys(MUSIC_GENRES);
